project:
  type: website
  output-dir: docs

website:
  title: "Samantha M Lewis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources.qmd
        text: Resources
        

format:
  html:
    theme: styles.scss
    mainfont: Elms Sans
    toc: true
    page-layout: full

editor: visual

